### ISSUE TITLE
Feature Suggestion: Please try out PyQt or PySide for the UI

### ISSUE THREAD

**Issue by srxcode** [Ishan-Karpe/PyDoc#1]
PyQt or PySide are relatively better for the UI, they have much better features. In future, switching might be difficult, so I think it would be a better way to start with them. A better practice is also to include a requirements.txt in the repo, it will help others to easily install all packages.(although its just limited to 1 for now, it would increase later on, so better start with this...)
Else, the project seems pretty fun.

**Comment by Ishan-Karpe** [comment]
Ok, will do that. For now though I'm happy with my final result so I will integrate this in a new project, sometime soon maybe this weekend. As for the requirements.txt I will add when you might need an API key or something like that. Thanks for the suggestion!
